# Generated by Django 2.2.7 on 2020-01-04 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_sec', '0002_auto_20200104_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account_sec.Gallery'),
        ),
    ]
